[package]
name = "cas"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
trees = { path = "../../" }
nom = "7.1.3"
rayon = "1.10.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
lazy_static = "1.5.0"
rand = "0.8.5"
